Selection tools refactor
sbrl/Minetest-WorldEditAdditions pull request #112
Opened 2024-09-30 14:55 UTC by VorTechnix

Refactor seems stable.

2024-09-30 21:16 UTC, sbrl requested changes
Overall, this is pretty awesome! Just got some small things to tidy up and then I think this should be ready to merge!

Tried to leave suggestions to make the process easier :-)

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +**REMOVED** in favour of `//srel`
```suggestion
```

Remove this line? It's already in the title so I'm unclear on why it still needs to stick around?

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +**REMOVED** in favour of `//srel`
Same here.
```suggestion
```

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +**REMOVED** in favour of `//srel`
Same here.
```suggestion
```

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +### `//scol [<axis1> ] <length>` (**REMOVED** in v1.15)
Perhaps this will be more obvious?
```suggestion
### `//scol [<axis1> ] <length>`
> [!WARNING]
> **REMOVED** in v1.15 in favour of [`//srel`](#srel)
```

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +### `//srect [<axis1> [<axis2>]] <length>` (**REMOVED** in v1.15)
Same here.
```suggestion
### `//srect [<axis1> [<axis2>]] <length>`
> [!WARNING]
> **REMOVED** in v1.15 in favour of [`//srel`](#srel)
```

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +### `//scube [<axis1> [<axis2> [<axis3>]]] <length>` (**REMOVED** in v1.15)
Same here.
```suggestion
### `//scube [<axis1> [<axis2> [<axis3>]]] <length>`
> [!WARNING]
> **REMOVED** in v1.15 in favour of [`//srel`](#srel)
```

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +### `//sfactor <mode:grow|shrink|average> <factor> [<target=xz>]` (**REMOVED** in v1.15)
Same here.
```suggestion
### `//sfactor <mode:grow|shrink|average> <factor> [<target=xz>]`
> [!WARNING]
> **REMOVED** in v1.15 in favour of [`//sgrow`](#sgrow) and [`//sshrink`](#sshrink)
```

2024-09-30 21:16 UTC, sbrl commented on Chat-Command-Reference.md
> +**REMOVED** in favour of `//sgrow` and `//sshrink`
Same here.
```suggestion
```

2024-09-30 21:16 UTC, sbrl commented on README.md
> + - [~~`//sfactor <mode:grow|shrink|average> <factor> [<target=xz>]`~~](https://worldeditadditions.mooncarrot.space/Reference/#sfactor) (REMOVED in v1.15)
This is all good! Great work.

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/init.lua
> +--- END DEPRECATED ---
Nice organisational touch. I like it!

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/init.lua
> +weac.register_alias("sshift", "shift", true) -- true = override target
I assume this commands are a superset of these commands? May be worth having entries in the chat command reference that simply point as aliases to the main entry?

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/scentre.lua
> +			Vector3.clone(wea_c.pos.get(name, 2))
Awesome, thanks for updating these.

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/scentre.lua
> +		wea_c.pos.set_all(name, {pos1, pos2})
`set_all` here will delete all other points - e.g. pos3+.

You'll want `set1` and `set2`. I've implemented a convenient alternative in set_multi ref 5fd0c3dad3ad4ad7cf53b9e6861d936a0d0de01d

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/scentre.lua
> +		return true, "Pos1 set to "..pos1..", Pos2 set to "..pos2
In the short form here, I generally treat pos1 / pos2 as variable names and don't capitalise?
```suggestion
		return true, "pos1 set to "..pos1..", pos2 set to "..pos2
```
....but given this message is shown to the user, then the full word is probably best here, unless we make a consistent decision to use pos1/pos2?
```suggestion
		return true, "position 1 set to "..pos1..", position 2 set to "..pos2

```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/scol.lua
> +	description = "Deprecated.",
```suggestion
	params = "None",
	description = "DEPRECATED: please use //srel instead.",
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/scube.lua
> +	description = "Deprecated.",
```suggestion
	params = "None",
	description = "DEPRECATED: please use //srel instead.",
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/sfactor.lua
> +	description = "Deprecated.",
```suggestion
	description = "DEPRECATED: please use //grow or //shrink instead.",

```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/sfactor.lua
> +	require_pos = 1,
Given this is a stub, then we could remove the pos requirement altogether?
```suggestion
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/srect.lua
> +	description = "Deprecated.",
```suggestion
	description = "DEPRECATED: please use //srel instead.",
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/srel.lua
> +		local vec, err = wea_c.parse.directions(params_text, facing, true)
Very nice and clean. You definitely know more about direction parsing in WEA than I do now!

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/sshift.lua
> +		if #ret < 1 then return false, "SSHIFT: No params found!"
Perhaps we can make this a little more user-friendly?
```suggestion
		if #ret < 1 then return false, "Error: No params found!"
```
.....given that the user is executing `//sshift` (or an alias thereof), then it should be obvious where the error comes from?

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/selectors/sshrink.lua
> +		if #ret < 1 then return false, "SSHRINK: No params found!"
Same here.
```suggestion
		if #ret < 1 then return false, "Error: No params found!"
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/uasparse.lua
> +		if #ret < 1 then return false, "UASPARSE: No params found!"
Same here.
```suggestion
		if #ret < 1 then return false, "Error: No params found!"
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_commands/commands/uasparse.lua
> +	description = "Returns min and max vectors for given inputs",
This is likely a debug command, no?
```suggestion
	description = "Debug command. Returns min and max vectors for given inputs",
```

2024-09-30 21:16 UTC, sbrl commented on worldeditadditions_core/utils/strings/split.lua
> +-- @param	dlm	string	The delimiter (separator) pattern (default: "%s+")
Got a neat trick for you here!
```suggestion
-- @param	dlm="%s+"	string	The delimiter (separator) pattern. If a falsey value is passed, then the default value is used.
```
Equals means default value :-)

2024-10-01 14:53 UTC, VorTechnix commented on worldeditadditions_commands/commands/selectors/init.lua
> +weac.register_alias("sshift", "shift", true) -- true = override target
Open an issue about this? I think this is something to do when we break our WE dependency cause right now this is a compatibility feature.

2024-10-01 18:27 UTC, sbrl commented
Looks great and ready to merge!

Could you resolve the conflicts at all please, @VorTechnix?

2024-10-01 18:52 UTC, merged